# https://manual.nssurge.com/dns/doh.html

[General]
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32,192.1.1.0/24,81.88.86.0/24,81.88.88.0/24,81.88.85.64/26,81.88.82.64/27,81.88.82.245/32,178.248.236.69/32,81.88.81.16/32,81.88.82.214/32,81.88.82.219/32,81.88.81.53/32,81.88.85.80/32,81.88.85.79/32,81.88.85.89/32,81.88.86.11/32,81.88.82.213/32

bypass-system = true

ipv6 = false
prefer-ipv6 = false

private-ip-answer = true

dns-direct-system = false

dns-fallback-system = false

dns-direct-fallback-proxy = true


dns-server = system
encrypted-dns-server = https://dns.adguard-dns.com/dns-query,https://dns.google/dns-query,https://cloudflare-dns.com/dns-query
fallback-dns-server = system
encrypted-dns-follow-outbound-mode = true

hijack-dns = :53

skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com,frsd.ru,*.frsd.ru,192.1.1.0/24,81.88.86.0/24,81.88.88.0/24,81.88.85.64/26,81.88.82.64/27,81.88.82.245/32,178.248.236.69/32,81.88.81.16/32,81.88.82.214/32,81.88.82.219/32,81.88.81.53/32,81.88.85.80/32,81.88.85.79/32,81.88.85.89/32,81.88.86.11/32,81.88.82.213/32,mangotele.com,mangosip.ru

# tun-included-routes = 

always-real-ip = *

icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT

update-url = https://raw.githubusercontent.com/pavel69/shadowrocket-configuration/refs/heads/release/conf/pf1.conf

[Proxy Group]
G1 = fallback,NL,IT,DE,policy-select-name=NL,interval=600,timeout=5,url=http://www.gstatic.com/generate_204

[Rule]
# Facetime UDP: 3478–3497, 16384–16387, 16393–16402

DST-PORT,3478-3497,PROXY
DST-PORT,16384–16387,PROXY
DST-PORT,16393–16402,PROXY

RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/main/rules/voice_ports.list,PROXY

RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/iCloud/iCloud.list,PROXY

RULE-SET,https://raw.githubusercontent.com/pavel69/shadowrocket-configuration/release/rules/pf/direct.list,DIRECT

RULE-SET,https://raw.githubusercontent.com/pavel69/shadowrocket-configuration/release/rules/pf/ip_test.list,PROXY
RULE-SET,https://raw.githubusercontent.com/pavel69/shadowrocket-configuration/release/rules/pf/proxy.list,G1

RULE-SET,https://github.com/toneywhitez/zkeen_rules/releases/latest/download/youtube.list,DE
RULE-SET,https://github.com/toneywhitez/zkeen_rules/releases/latest/download/youtube_ips.list,DE,no-resolve
RULE-SET,https://github.com/toneywhitez/zkeen_rules/releases/latest/download/telegram_ips.list,G1,no-resolve
RULE-SET,https://github.com/toneywhitez/zkeen_rules/releases/latest/download/meta_ips.list,G1,no-resolve

RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/main/rules/domains_community.list,DE
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/main/rules/domain_ips.list,DE,no-resolve

RULE-SET,https://raw.githubusercontent.com/HybridNetworks/whatsapp-cidr/main/WhatsApp/whatsapp_cidr_ipv4.list,G1,no-resolve
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,G1

FINAL,DIRECT
